languageCode = "fr"
languageName = "Français"
weight = 2
title = "Blowfish"

[params]
  displayName = "Français"
  isoCode = "fr"
  rtl = false
  dateFormat = "2 janvier 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "Un thème puissant et léger pour Hugo."

[params.author]
  name = "Blowfish"
  image = "img/blowfish_logo.png"
  headline = "Un thème puissant et léger pour Hugo."
  bio = "Un thème puissant et léger pour Hugo."
  links = [
    { x-twitter = "https://twitter.com/burufugu" },
    { github = "https://github.com/nunocoracao/blowfish" },
  ]
