languageCode = "ja"
languageName = "日本語"
weight = 2
title = "Blowfish"

[params]
  displayName = "日本語"
  isoCode = "ja"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "強力で、軽量な Hugo のテーマです。"

[author]
  name = "Blowfish"
  image = "img/blowfish_logo.png"
  headline = "強力で、軽量な Hugo のテーマです。"
  bio = "強力で、軽量な Hugo のテーマです。"
  links = [
    { x-twitter = "https://twitter.com/burufugu" },
    { github = "https://github.com/nunocoracao/blowfish" },
  ]
