languageCode = "de"
languageName = "Deutsch"
weight = 3
title = "Blowfish"

[params]
  displayName = "Deutsch"
  isoCode = "de"
  rtl = false
  dateFormat = "2. January 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "Ein leistungsstarkes, leichtgewichtiges Theme für Hugo."

[params.author]
  name = "Blowfish"
  image = "img/blowfish_logo.png"
  headline = "Ein leistungsstarkes, leichtgewichtiges Theme für Hugo."
  bio = "Ein leistungsstarkes, leichtgewichtiges Theme für Hugo."
  links = [
    { x-twitter = "https://twitter.com/burufugu" },
    { github = "https://github.com/nunocoracao/blowfish" },
  ]
