languageCode = "es"
languageName = "Español"
weight = 6
title = "Blowfish"

[params]
  displayName = "Español"
  isoCode = "es"
  rtl = false
  dateFormat = "2 de January de 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "Un tema potente y ligero para Hugo."

[params.author]
  name = "Blowfish"
  image = "img/blowfish_logo.png"
  headline = "Un tema potente y ligero para Hugo."
  bio = "Un tema potente y ligero para Hugo."
  links = [
    { x-twitter = "https://twitter.com/burufugu" },
    { github = "https://github.com/nunocoracao/blowfish" },
  ]
