languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Blowfish"
logo = "img/blowfish_logo_transparent.png"
description = "A powerful, lightweight theme for Hugo built with Tailwind CSS."
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
  name = "Blowfish"
  image = "img/blowfish_logo.png"
  headline = "A powerful, lightweight theme for Hugo built with Tailwind CSS."
  bio = "A powerful, lightweight theme for Hugo built with Tailwind CSS."
  links = [
    { twitter = "https://twitter.com/burufugu" },
    { mastodon = "https://masto.ai/@blowfish" },
    { github = "https://github.com/nunocoracao/blowfish" },
  ]
