# -- Menu Principal --
# O menu principal é exibido no cabeçalho no topo da página.

[[main]]
  name = "Documentação"
  pageRef = "docs"
  weight = 10

[[main]]
  name = "Shortcodes"
  pageRef = "docs/shortcodes"
  weight = 15

[[main]]
  name = "Exemplos"
  weight = 20

[[main]]
  name = "Amostras"
  parent = "Exemplos"
  pageRef = "samples"
  weight = 16

[[main]]
  name = "Galeria"
  parent = "Exemplos"
  pageRef = "examples"
  weight = 30

[[main]]
  name = "Receitas"
  parent = "Exemplos"
  pageRef = "guides"
  weight = 40

[[main]]
  name = "Usuários"
  pageRef = "users"
  weight = 90

[[main]]
  name = "Merch"
  url = "https://www.teepublic.com/user/blowfish-store/t-shirts"
  weight = 100

[[main]]
  identifier = "twitter"
  pre = "x-twitter"
  url = "https://twitter.com/burufugu"
  weight = 200

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/nunocoracao/blowfish"
  weight = 400


# -- Menu de Rodapé --

 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "Autores"
   pageRef = "authors"
   weight = 20
