name: Create ZIP
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: zip -r config-default.zip config/_default
      - uses: actions/upload-artifact@v4
        with:
          name: config-default
          path: config-default.zip
      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: config-default.zip
          tag_name: ${{ github.event.release.tag_name }}
